### ISSUE TITLE
Flake8

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [gammapy/gammapy#3551]
**Gammapy version**

Current `@master`.

**Bug description**

Lots of [Flake8](https://github.com/pycqa/flake8) alerts.

**Expected behavior**

Very few alerts, or even better None.

**To Reproduce**

Run `flake8` in a clone of the repository.

**Other information**

While most issues are cosmetic to minor, there are real issues in the code, such as duplicated functions:
```
./gammapy/data/tests/test_observations.py:226:1: F811 redefinition of unused 'test_observation' from line 25
```

**Comment by adonath** [comment]
After #3550 there are still many flake8 warnings, but I'll take sometime this afternoon to clean up the whole code base again.

**Comment by DimitriPapadopoulos** [comment]
Yes, I fixed part of the alerts only. I see the rest of the alerts as questionable.

It might be more interesting to format the code with [black](https://github.com/psf/black). I must say I wasn't a fan of this code formatter (too opinionated and with opinions sometimes different from mine), but once you get used to it, formatted code is really much easier to read and maintain.

**Comment by adonath** [comment]
@DimitriPapadopoulos Yes, we use `black` already for Gammapy. But I think the code base is not up to date formatted.

**Comment by DimitriPapadopoulos** [comment]
The releasing alerts are mostly formatting issues. If you formatb the files with black, most of them should disappear.

**Comment by adonath** [comment]
Perfect thanks! For now I'll close the issue. If significant flake8 issue remain I'll reopen.

**Comment by adonath** [comment]
I addressed remaining flake8 issues in https://github.com/gammapy/gammapy/commit/bde022a8c8070333cc766cae094181004115b9a8/ Thanks again @DimitriPapadopoulos!
