### ISSUE TITLE
Setup Tests Fail

### ISSUE THREAD

**Issue by dlennarz** [gammapy/gammapy#366]
I just updated my fork to the latest gammapy:master and also updated the python packages. I have two different installations on different systems with different packages available.

For both installation I get an import error (ERROR collecting gammapy/scripts/tests/test_all.py, gammapy/scripts/data_show.py:10  import click, E   ImportError: No module named 'click').

On one installation, I get the additional error 
```
E ImportError: /tmp/gammapy-test-6jwp31bv/lib.linux-x86_64-3.4/gammapy/detect/_test_statistics_cython.cpython-34m.so: undefined symbol: _Py_ZeroStruct).
```

**Comment by cdeil** [comment]
Concerning [click](http://click.pocoo.org/), this is now a dependency that's needed to run the Gammapy tests. I've mentioned it here:  https://gammapy.readthedocs.org/en/latest/install.html#dependencies

click is an optional dependency, the problem is that it's most conveniently used for decorators, so it's not easily possible to put that import into a function:
https://github.com/gammapy/gammapy/blob/master/gammapy/scripts/data_show.py#L10
And then the zealous pytest test discovery imports every sub-module and fails if you don't have click.

It is possible to make click optional for tests, but for now, the quick fix is to install it.

Concerning the undefined symbol error ... I don't know.
Maybe if you post the full output of these commands in a [gist](https://gist.github.com/) I'll be able to tell you what the issue is:
```
git clone https://github.com/gammapy/gammapy.git gammapy-test-cython
cd gammapy-test-cython
python setup.py build
python setup.py test
```

**Comment by dlennarz** [comment]
I tried to attach a text file to the issue, but that did not work. Here is the output:
https://gist.github.com/dlennarz/9261316889e166f55574

**Comment by cdeil** [comment]
@dlennarz – You only posted the output of `python setup.py test` that shows that there's an issue with the `_test_statistics_cython.cpython-34m.so` library:
https://gist.github.com/dlennarz/9261316889e166f55574#file-error_2-txt-L376

In order to diagnose what's wrong the output of `python setup.py build` is needed, i.e. which Python / Cython / C compiler was used to generate it.

Can you please run the commands I posted above, i.e. run the build in a fresh directory to make sure there's no old generated C or so files around.

**Comment by dlennarz** [comment]
I'm sorry, so there are the two test errors I am getting:
https://gist.github.com/dlennarz/3015a404d6894b81bc5c
https://gist.github.com/dlennarz/9261316889e166f55574

This is the build output for the second test error:
https://gist.github.com/dlennarz/ec862d20aade57cdbc8a

I started with a completely fresh checkout.

**Comment by dlennarz** [comment]
Concerning click, I don't see it mentioned on this page:
https://gammapy.readthedocs.org/en/latest/install.html#dependencies

**Comment by cdeil** [comment]
> Concerning click, I don't see it mentioned on this page:
https://gammapy.readthedocs.org/en/latest/install.html#dependencies

Clear your browser cache and refresh.

I merged this earlier today:
https://github.com/gammapy/gammapy/pull/352/files#diff-62c330cd8da31d476bb63b51bb8b1307
(and yes, the install instructions can be improved ...)

**Comment by cdeil** [comment]
I don't understand yet what's wrong with your compile / linking here:
```
/usr/bin/gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/software/git/1.7.11.5--GCC-4.4.5/include -I/opt/software/ClusterStudio/2013sp1/composer_xe_2013_sp1.0.080/mkl/include/fftw -I/opt/software/ClusterStudio/2013sp1/composer_xe_2013_sp1.0.080/mkl/include -I/opt/software/Python/2.7.2--GCC-4.4.5/include -I/opt/software/boost/1.47.0--GCC-4.4.5/include -I/opt/software/ClusterStudio/2011.0/composerxe-2011.5.220/tbb/include -I/opt/software/OpenMPI/1.4.3--GCC-4.4.5/include -fPIC -I/mnt/research/IceCube/dlennarz/software/python/miniconda/3.16.0/include/python3.4m -c gammapy/_compiler.c -o build/temp.linux-x86_64-3.4/gammapy/_compiler.o
gcc -pthread -shared -L/mnt/research/IceCube/dlennarz/software/python/miniconda/3.16.0/lib -Wl,-rpath=/mnt/research/IceCube/dlennarz/software/python/miniconda/3.16.0/lib,--no-as-needed -I/opt/software/git/1.7.11.5--GCC-4.4.5/include -I/opt/software/ClusterStudio/2013sp1/composer_xe_2013_sp1.0.080/mkl/include/fftw -I/opt/software/ClusterStudio/2013sp1/composer_xe_2013_sp1.0.080/mkl/include -I/opt/software/Python/2.7.2--GCC-4.4.5/include -I/opt/software/boost/1.47.0--GCC-4.4.5/include -I/opt/software/ClusterStudio/2011.0/composerxe-2011.5.220/tbb/include -I/opt/software/OpenMPI/1.4.3--GCC-4.4.5/include build/temp.linux-x86_64-3.4/gammapy/_compiler.o -L/mnt/research/IceCube/dlennarz/software/python/miniconda/3.16.0/lib -lpython3.4m -o build/lib.linux-x86_64-3.4/gammapy/_compiler.cpython-34m.so
cythoning gammapy/detect/_test_statistics_cython.pyx to gammapy/detect/_test_statistics_cython.c
building 'gammapy.detect._test_statistics_cython' extension
creating build/temp.linux-x86_64-3.4/gammapy/detect
/usr/bin/gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/software/git/1.7.11.5--GCC-4.4.5/include -I/opt/software/ClusterStudio/2013sp1/composer_xe_2013_sp1.0.080/mkl/include/fftw -I/opt/software/ClusterStudio/2013sp1/composer_xe_2013_sp1.0.080/mkl/include -I/opt/software/Python/2.7.2--GCC-4.4.5/include -I/opt/software/boost/1.47.0--GCC-4.4.5/include -I/opt/software/ClusterStudio/2011.0/composerxe-2011.5.220/tbb/include -I/opt/software/OpenMPI/1.4.3--GCC-4.4.5/include -fPIC -I/mnt/research/IceCube/dlennarz/software/python/miniconda/3.16.0/lib/python3.4/site-packages/numpy/core/include -I/mnt/research/IceCube/dlennarz/software/python/miniconda/3.16.0/include/python3.4m -c gammapy/detect/_test_statistics_cython.c -o build/temp.linux-x86_64-3.4/gammapy/detect/_test_statistics_cython.o -Wp,-w -Wno-unused-function
gcc -pthread -shared -L/mnt/research/IceCube/dlennarz/software/python/miniconda/3.16.0/lib -Wl,-rpath=/mnt/research/IceCube/dlennarz/software/python/miniconda/3.16.0/lib,--no-as-needed -I/opt/software/git/1.7.11.5--GCC-4.4.5/include -I/opt/software/ClusterStudio/2013sp1/composer_xe_2013_sp1.0.080/mkl/include/fftw -I/opt/software/ClusterStudio/2013sp1/composer_xe_2013_sp1.0.080/mkl/include -I/opt/software/Python/2.7.2--GCC-4.4.5/include -I/opt/software/boost/1.47.0--GCC-4.4.5/include -I/opt/software/ClusterStudio/2011.0/composerxe-2011.5.220/tbb/include -I/opt/software/OpenMPI/1.4.3--GCC-4.4.5/include build/temp.linux-x86_64-3.4/gammapy/detect/_test_statistics_cython.o -L/mnt/research/IceCube/dlennarz/software/python/miniconda/3.16.0/lib -lpython3.4m -o build/lib.linux-x86_64-3.4/gammapy/detect/_test_statistics_cython.cpython-34m.so
copying gammapy/cython_version.py -> build/lib.linux-x86_64-3.4/gammapy
```
It looks like you use `/usr/bin/gcc` to compile and then `gcc` to link. Is that the same compiler?
The Intel compiler includes probably shouldn't be there ... maybe you have environment variables like CCFLAGS set that communicate to the Python build they should be used?

Maybe, if you just want to work on your pull request for now, we just ignore this issue?
Note that you can use `python setup.py test -V -t  gammapy/stats/tests/test_feldman_cousins.py` to run your test ... for this the `_test_statistics_cython.cpython-34m.so` issue doesn't matter.

**Comment by dlennarz** [comment]
Yes, refreshing the browser did make me see the click instructions.

I found the issue. The compilation was pulling in $CPPFLAGS, which contained -I/opt/software/Python/2.7.2--GCC-4.4.5/include. After removing that the error went away and the tests complete fine on that machine.

On the other machine I still have the error:
E                                    astropy.units.core.UnitsError: Can only apply 'add' function to dimensionless quantities when other argument is not a quantity (unless the latter is all zero/infinity/nan)

It looks like my two installations are running with different versions of astropy. The version giving me the error is (1.0.5 np110py34_1), the one that works is (1.0.4, np19py34_0). That is an issue somebody should look at.

For some strange reason "conda update --all" is not updating astropy on the machine where everything works right now. "conda update astropy" will update astropy and numpy, but I don't want to do that right now.

**Comment by cdeil** [comment]
I saw the `astropy.units.core.UnitsError`s yesterday and fixed the ~10 occurences in Gammapy and the Gammapy tests  in #352.
Do you still see them when you update to Gammapy master?

I didn't track down what caused the `astropy.units.core.UnitsError`s ... I think the Astropy Quantity implementation got stricter, forbidding computations now like `a + b` where `a` is a Quantity with a unit, and `b` is a simple number or numpy array. Before this worked and assumed that `b` also represented a quantity of the same unit as `a`, now it fails with that `UnitError`.

**Comment by dlennarz** [comment]
Yes, I do see this in the gammapy master.

It seems to be in this line:
return all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan)

My guess is that atol and rtol are a quantity with unit and an array.

**Comment by cdeil** [comment]
The test_wcs_object failure should be fixed by #368.
@dlennarz – Can we close this ticket or is there some issue left?

**Comment by dlennarz** [comment]
All issues have been resolved.
