### ISSUE TITLE
Reuse SpectrumSimulation in CTASpectrumObservation

### ISSUE THREAD

**Issue by joleroi** [gammapy/gammapy#876]
In https://github.com/gammapy/gammapy/pull/875 the class [CTASpectrumObservation](https://github.com/gammapy/gammapy/blob/master/gammapy/scripts/cta_utils.py#L114) was added. It should be refactored to result the functionality already available in ``SpectrumSimulation``. I think the necessary steps are the following

* [ ] Make CTA background available as [TableModel](https://github.com/gammapy/gammapy/blob/master/gammapy/scripts/cta_utils.py#L114). The problem is that the CTA background is given as rate/bin. I guess, it would be possible to divide the rate by the bin width and place it as interpolation node at the (log) bin center. This would give an integrable model that can be used in ``SpectrumSimulation``.
* [ ] Remove folding of the background model in ``SpectrumSimulation``. At the moment the background model is folded with the source IRFs, in  [SpectrumSimulation.npred_background](https://github.com/gammapy/gammapy/blob/master/gammapy/spectrum/simulation.py#L69). This is probably a bad idea and should be changed, since background models will typically be given in counts space. Either this has to be implemented in ``calculated_predicted_counts`` (which should be refactored as a class) or as model integration * livetime in ``npred_background``

This should already be it. More improvement in ``CTASpectrumObservation`` could be done after that.

**Comment by cdeil** [comment]
@registerrier agreed to do this. See https://github.com/gammapy/gammapy/issues/1551#issuecomment-408381049 .

**Comment by registerrier** [comment]
Background is usually estimated as a count-rate per bin.  In that sense, background models should not be evaluated and differ from `TableModel`. Actually, they are not even a `SpectralModel` which is implicitly assumed to be convolved to yield predicted counts in `reco` space. We will have to introduce such models but in the meantime we need a workaround.

A possibility is to pass simply an array, but we have no way to ensure that the binning is consistent with the `edisp`. We can simply pass a `NDDataArray` instead.  In that case `predict_background` is indeed only the product of `livetime * background_model`.

**Comment by cdeil** [comment]
The goal is to make spectrum simulation with the CTA background models in `s^-1 MeV^-1 sr^-1` work with `SpectrumSimulation`, no?

- https://gamma-astro-data-formats.readthedocs.io/en/latest/irfs/full_enclosure/bkg/index.html
- https://docs.gammapy.org/dev/api/gammapy.spectrum.SpectrumSimulation.html

> background models should not be evaluated

The binning used in the background model creation is usually different from the binning one wants to use for analysis / simulation. To me that makes sense to treat such background models like sky models or IRFs and allow evaluate at arbitrary energies, and integration over user-chosen energy bins.

> We will have to introduce such models but in the meantime we need a workaround.
> A possibility is to pass simply an array

Did you try `TableModel` for background in `s^-1 MeV^-1 sr^-1`? Maybe evaluate just works there, or can be made to work with small effort, by allowing `table_model.values` to be a quantity with the appropriate units?

- https://docs.gammapy.org/dev/api/gammapy.spectrum.models.TableModel.html

If this doesn't work, maybe introduce a `BackgroundTableModel` directly? Is this the way to go?

@adonath and I discussed a bit at lunch today about background modeling. @adonath - Do you want to chime in here, or open a new issue with suggestions concerning 1D and 3D background models?

Is a workaround solution for v0.9 helpful? It'll break the API, and then it'll break again in v0.10. So better to work towards a proper solution directly, and to defer to v0.10 if not ready for v0.9, no?

**Comment by cdeil** [comment]
I guess it's a matter of taste what functionality to put in `SpectrumSimulation` and what elsewhere.

Note the related https://github.com/gammapy/gammapy/issues/1551#issuecomment-414378034 - I see that in the old code by Julien the energy integration was indeed done outside the spectrum simulation class.

On the other hand, note that SpectrumSimulation does take a spectral model and not just an npred vector - one could argue that one wants to vary background model just like one wants to vary source models as part of a spectrum simulation.

I haven't thought about it much, but I don't think I really have a preference for how you organise the code.

It might be a good idea to start with https://github.com/gammapy/gammapy/issues/1551#issuecomment-414378034 and first polish the small classes to load and "reduce" or "prepare" the IRFs, and maybe even use them in
https://docs.gammapy.org/dev/notebooks/simulate_3d.html first where it's simpler, and only then to adapt SpectrumSimulation and SensitivityEstimator to the new classes. I think in Barcelona we already discussed this, and the idea was to keep two classes, one for "raw" and one for "reduced" IRFs. If we do that, indeed probably it would be easiest if the spectrum simulation takes "reduced" IRFs. I'm not exactly clear on what that should contain for background, but like I said: I think I don't have a strong preference on who exactly does the "reduce" step, suggest to just go ahead with a first small PR and put what you like best.

**Comment by registerrier** [comment]
With the introduction of the PIG dataset (#1986 ), the plan for a specific spectral `BackgroundModel` is more clear. `SpectrumSimulation` will rely on it.
I postpone to v0.11 after the introduction of the background model.

**Comment by registerrier** [comment]
This is close to being solved by the introduction SpectrumDatasetOnOff. Postponing to v0.13 for now.

**Comment by adonath** [comment]
The `SpectrumSimulation` class was removed in #2305 and replaced with a `SpectrumDatasetOnOff.fake()` method, which allows to specify the background rate as a `CountsSpectrum`.  However the abstraction of a `BackgroundModel` for spectral analysis including parameters is still missing...
